### PR TITLE
generate_freeldr_ini: Correctly acquire target file path on Win32

### PR DESCRIPTION
**Pull request by archeYR**
Write freeldr.ini on target USB drive instead of executable path.

### CODE REVIEW

**Comment by abt2804** [comment]
> Write freeldr.ini on target USB drive instead of executable path.

Actually the variable `mounted_path` was supposed to be a pointer to `pvariables->partitions[pvariables->current_partition]` however I instead I wrote it like this.
` pvariables->is_partition_mounted = pvariables->partitions[pvariables->current_partition];`
Which is why it wasn't working.
Basically it was meant for Linux version to obtain the mounted path of the partition however I forgot to adapt it for Windows properly. (As I was just going to treat it as a pointer of the allocated variable which specified actual volume of the drive instead) Hence let me create a commit for the proper fix. Thanks for letting me know about this issue,

**Comment by abt2804** [comment]
@archeYR Please test again.

**Comment by archeYR** [comment]
Works properly now @arnavbhatt288 
fixed

**Comment by abt2804** [comment]
@archeYR nice

**Pull request closed without merging**
